services:
  sdm-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sdm-backend-js
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    restart: unless-stopped
